from myPyllant.const import COUNTRIES as MYPYLLANT_COUNTRIES

DOMAIN = "mypyllant"
OPTION_UPDATE_INTERVAL = "update_interval"
OPTION_COUNTRY = "country"
DEFAULT_UPDATE_INTERVAL = 60
DEFAULT_QUICK_VETO_DURATION = 3
COUNTRIES = MYPYLLANT_COUNTRIES
DEFAULT_COUNTRY = "germany"
