DOMAIN = "mypyllant"
OPTION_UPDATE_INTERVAL = "update_interval"
OPTION_REFRESH_DELAY = "refresh_delay"
OPTION_DEFAULT_QUICK_VETO_DURATION = "quick_veto_duration"
OPTION_COUNTRY = "country"
OPTION_BRAND = "brand"
DEFAULT_UPDATE_INTERVAL = 60  # in seconds
DEFAULT_REFRESH_DELAY = 5  # in seconds
DEFAULT_COUNTRY = "germany"
QUOTA_PAUSE_INTERVAL = 3 * 3600  # in seconds

SERVICE_SET_QUICK_VETO = "set_quick_veto"
SERVICE_SET_MANUAL_MODE_SETPOINT = "set_manual_mode_setpoint"
SERVICE_CANCEL_QUICK_VETO = "cancel_quick_veto"
SERVICE_SET_HOLIDAY = "set_holiday"
SERVICE_CANCEL_HOLIDAY = "cancel_holiday"
SERVICE_SET_ZONE_TIME_PROGRAM = "set_zone_time_program"
SERVICE_SET_DHW_TIME_PROGRAM = "set_dhw_time_program"
SERVICE_SET_DHW_CIRCULATION_TIME_PROGRAM = "set_dhw_circulation_time_program"
